Check if Docker is operable

diff --git a/share/galaxy-debug b/share/galaxy-debug
--- a/share/galaxy-debug
+++ b/share/galaxy-debug
@@ -2,12 +2,19 @@
 
 set -eu
 
+docker --version &> /dev/null || true
+
+if [ ! $? -ne 0 ]
+then
+    echo -e "\e[31mError! Docker not found. Ensure Docker is installed and running.\e[0m"
+    exit 1
+fi
+
 if [ ! -f 'tests/main.yml' ]
 then
     echo -e "\e[31mError! Tests not found. Ensure you're in the right directory.\e[0m"
     exit 1
 fi
-
 
 arguments=()
 platform="fedora:37"
